# Generated by Django 5.2.6 on 2025-09-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('audio', models.FileField(upload_to='episodes/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
